#!/usr/bin/env bash
# One-shot installer for the autodl-openai-gateway on a small Linux VPS.
# Run as a regular user with sudo access; the script will sudo internally.
#
#   bash deploy/install.sh                    # install to /opt/autodl-openai-gateway, port 8765
#   GATEWAY_PORT=9000 bash deploy/install.sh  # listen on :9000 instead
#
# Recognized env vars (all optional):
#   INSTALL_DIR        target dir (default /opt/autodl-openai-gateway)
#   SERVICE_NAME       systemd unit name (default autodl-openai-gateway)
#   GATEWAY_PORT       port the app listens on (default 8765)
#   GATEWAY_HOST       bind address (default 0.0.0.0)
#   AUTODL_BASE_URL    upstream base URL
#   AUTODL_BOOTSTRAP_TOKEN  token used to seed the workflow cache at startup
#   CORS_ORIGINS       comma-separated allowed origins (default *)
#   LOG_FILE           log file path (default logs/gateway.log; "" = stderr only)
#   LOG_LEVEL          root logger level (default INFO)
#   Any TIMEOUT_* / MAX_* knob from app.settings.Settings is also forwarded.
#
# All of these are written to /etc/autodl-openai-gateway.env and read by the
# systemd unit's EnvironmentFile directive.
#
# Re-running is safe: it reinstalls the venv in place, rewrites the env file,
# and re-enables the systemd unit.

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/autodl-openai-gateway}"
SERVICE_NAME="${SERVICE_NAME:-autodl-openai-gateway}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
ENV_FILE="/etc/autodl-openai-gateway.env"

if ! command -v sudo >/dev/null 2>&1; then
    echo "sudo is required" >&2
    exit 1
fi

if ! command -v systemctl >/dev/null 2>&1; then
    echo "systemctl is required (this installer targets systemd hosts)" >&2
    exit 1
fi

echo "==> Installing into $INSTALL_DIR"
sudo mkdir -p "$INSTALL_DIR"
sudo chown "$USER":"$USER" "$INSTALL_DIR"

# Copy the project (assumes we're running from the repo root).
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
sudo rsync -a --delete \
    --exclude='.venv' \
    --exclude='__pycache__' \
    --exclude='.pytest_cache' \
    --exclude='.git' \
    "$PROJECT_ROOT"/ "$INSTALL_DIR"/

echo "==> Creating venv + installing dependencies"
"$PYTHON_BIN" -m venv "$INSTALL_DIR/.venv"
"$INSTALL_DIR/.venv/bin/pip" install -q -U pip
"$INSTALL_DIR/.venv/bin/pip" install -q -r "$INSTALL_DIR/requirements.txt"

echo "==> Writing environment file to $ENV_FILE"
# Build a key=value file from the current environment, but ONLY for keys the
# gateway actually understands. This keeps secrets like AWS_* etc. from
# leaking into the service.
declare -a KNOWN_KEYS=(
    GATEWAY_HOST GATEWAY_PORT LOG_LEVEL LOG_FILE LOG_MAX_BYTES LOG_BACKUP_COUNT
    AUTODL_BASE_URL AUTODL_BOOTSTRAP_TOKEN
    TIMEOUT_CONNECT TIMEOUT_READ TIMEOUT_SUBMIT TIMEOUT_WRITE TIMEOUT_POOL
    MAX_CONNECTIONS MAX_KEEPALIVE KEEPALIVE_EXPIRY
    CORS_ORIGINS SKIP_STARTUP_SYNC
)
TMP_ENV="$(mktemp)"
trap 'rm -f "$TMP_ENV"' EXIT
{
    echo "# Generated by deploy/install.sh on $(date -u +%FT%TZ)"
    echo "# Edit this file and 'sudo systemctl restart $SERVICE_NAME' to apply."
    echo
    for key in "${KNOWN_KEYS[@]}"; do
        # Only emit a line if the variable is actually set in our shell.
        if [ -n "${!key-}" ]; then
            # Quote values so spaces / commas / globs survive.
            printf '%s=%q\n' "$key" "${!key}"
        fi
    done
} >"$TMP_ENV"
sudo install -m 0640 -o root -g root "$TMP_ENV" "$ENV_FILE"

echo "==> Installing systemd unit"
sudo cp "$INSTALL_DIR/deploy/$SERVICE_NAME.service" \
    /etc/systemd/system/$SERVICE_NAME.service
sudo systemctl daemon-reload
sudo systemctl enable --now "$SERVICE_NAME"

echo "==> Verifying"
# Use the port we *actually* configured, falling back to 8765 if unset.
VERIFY_PORT="${GATEWAY_PORT:-8765}"
sleep 1
if curl -fsS "http://127.0.0.1:${VERIFY_PORT}/healthz" >/dev/null; then
    echo "==> OK: gateway is responding on :${VERIFY_PORT}"
else
    echo "==> WARNING: /healthz did not return 200 on :${VERIFY_PORT}; check:" >&2
    echo "    sudo journalctl -u $SERVICE_NAME -n 50" >&2
    exit 1
fi

echo
echo "Done. Useful commands:"
echo "  sudo systemctl status  $SERVICE_NAME"
echo "  sudo journalctl -fu     $SERVICE_NAME"
echo "  sudo systemctl restart  $SERVICE_NAME"
echo
echo "The service is reachable at http://<server-public-ip>:${VERIFY_PORT}/v1"
echo "Health probe: curl http://127.0.0.1:${VERIFY_PORT}/healthz"
echo "Env file (edit then restart): sudo \$EDITOR $ENV_FILE"