#!/usr/bin/env bash
# One-shot installer for the autodl-openai-gateway on a small Linux VPS.
# Run as a regular user with sudo access; the script will sudo internally.
#
#   bash deploy/install.sh                    # install to /opt/autodl-openai-gateway, port 8765
#   GATEWAY_PORT=9000 bash deploy/install.sh  # listen on :9000 instead
#
# Recognized env vars (all optional):
#   INSTALL_DIR        target dir (default /opt/autodl-openai-gateway)
#   SERVICE_NAME       systemd unit name (default autodl-openai-gateway)
#   GATEWAY_PORT       port the app listens on (default 8765)
#   GATEWAY_HOST       bind address (default 0.0.0.0)
#   AUTODL_BASE_URL    upstream base URL
#   AUTODL_BOOTSTRAP_TOKEN  token used to seed the workflow cache at startup
#   CORS_ORIGINS       comma-separated allowed origins (default *)
#   LOG_FILE           log file path (default logs/gateway.log; "" = stderr only)
#   LOG_LEVEL          root logger level (default INFO)
#   LOG_UPSTREAM_RESPONSES  set to 1 to log a DEBUG digest of every AutoDL response
#   STOP_FIRST         set to 0 to skip the "stop the running service
#                      before reinstall" step (default 1). Set 0 only if
#                      you know what you're doing — concurrent rsync over
#                      a live process can race with code reads.
#   Any TIMEOUT_* / MAX_* knob from app.settings.Settings is also forwarded.
#
# All of these are written to /etc/autodl-openai-gateway.env and read by the
# systemd unit's EnvironmentFile directive.
#
# Re-running is safe: by default it stops any running instance, reinstalls
# the venv in place, rewrites the env file, and re-enables the systemd
# unit. Set STOP_FIRST=0 to keep the old service running while files are
# being swapped (only useful for hot-reload-style workflows; usually you
# want the default).

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/autodl-openai-gateway}"
SERVICE_NAME="${SERVICE_NAME:-autodl-openai-gateway}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
ENV_FILE="/etc/autodl-openai-gateway.env"

if ! command -v sudo >/dev/null 2>&1; then
    echo "sudo is required" >&2
    exit 1
fi

if ! command -v systemctl >/dev/null 2>&1; then
    echo "systemctl is required (this installer targets systemd hosts)" >&2
    exit 1
fi

# Stop the existing service (if any) before we start swapping code underneath
# it. rsync on a live Python process can race with .pyc writes and cause
# ImportError on the next restart. STOP_FIRST=0 opts out of this safety net.
STOP_FIRST="${STOP_FIRST:-1}"
if [ "$STOP_FIRST" = "1" ]; then
    # `systemctl is-active` exits 0 when running, 3 when inactive, 4 when
    # the unit is not loaded. Catch the "not installed yet" case so this
    # works for fresh installs too.
    if sudo systemctl is-active --quiet "$SERVICE_NAME" 2>/dev/null; then
        echo "==> Stopping existing $SERVICE_NAME service"
        # TimeoutStopSec=15 in the unit caps how long this can wait.
        sudo systemctl stop "$SERVICE_NAME"
    elif sudo systemctl list-unit-files "$SERVICE_NAME.service" 2>/dev/null \
            | grep -q "^$SERVICE_NAME.service"; then
        # Unit is known to systemd but inactive — nothing to stop, but log
        # it so the user sees we're aware of the prior install.
        echo "==> $SERVICE_NAME is installed but inactive; no stop needed"
    else
        echo "==> No existing $SERVICE_NAME unit; nothing to stop"
    fi
else
    echo "==> STOP_FIRST=0: leaving the running service untouched during install"
fi

echo "==> Installing into $INSTALL_DIR"
sudo mkdir -p "$INSTALL_DIR"
sudo chown "$USER":"$USER" "$INSTALL_DIR"

# Copy the project (assumes we're running from the repo root).
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
sudo rsync -a --delete \
    --exclude='.venv' \
    --exclude='__pycache__' \
    --exclude='.pytest_cache' \
    --exclude='.git' \
    "$PROJECT_ROOT"/ "$INSTALL_DIR"/

echo "==> Creating venv + installing dependencies"
"$PYTHON_BIN" -m venv "$INSTALL_DIR/.venv"
"$INSTALL_DIR/.venv/bin/pip" install -q -U pip
"$INSTALL_DIR/.venv/bin/pip" install -q -r "$INSTALL_DIR/requirements.txt"

echo "==> Writing environment file to $ENV_FILE"
# Build a key=value file from the current environment, but ONLY for keys the
# gateway actually understands. This keeps secrets like AWS_* etc. from
# leaking into the service.
declare -a KNOWN_KEYS=(
    GATEWAY_HOST GATEWAY_PORT LOG_LEVEL LOG_FILE LOG_MAX_BYTES LOG_BACKUP_COUNT LOG_UPSTREAM_RESPONSES
    AUTODL_BASE_URL AUTODL_BOOTSTRAP_TOKEN
    TIMEOUT_CONNECT TIMEOUT_READ TIMEOUT_SUBMIT TIMEOUT_WRITE TIMEOUT_POOL
    MAX_CONNECTIONS MAX_KEEPALIVE KEEPALIVE_EXPIRY
    CORS_ORIGINS SKIP_STARTUP_SYNC
)
TMP_ENV="$(mktemp)"
trap 'rm -f "$TMP_ENV"' EXIT
{
    echo "# Generated by deploy/install.sh on $(date -u +%FT%TZ)"
    echo "# Edit this file and 'sudo systemctl restart $SERVICE_NAME' to apply."
    echo
    for key in "${KNOWN_KEYS[@]}"; do
        # Only emit a line if the variable is actually set in our shell.
        if [ -n "${!key-}" ]; then
            # Quote values so spaces / commas / globs survive.
            printf '%s=%q\n' "$key" "${!key}"
        fi
    done
} >"$TMP_ENV"
sudo install -m 0640 -o root -g root "$TMP_ENV" "$ENV_FILE"

echo "==> Installing systemd unit"
sudo cp "$INSTALL_DIR/deploy/$SERVICE_NAME.service" \
    /etc/systemd/system/$SERVICE_NAME.service
sudo systemctl daemon-reload
sudo systemctl enable --now "$SERVICE_NAME"

echo "==> Verifying"
# Use the port we *actually* configured, falling back to 8765 if unset.
VERIFY_PORT="${GATEWAY_PORT:-8765}"
sleep 1
if curl -fsS "http://127.0.0.1:${VERIFY_PORT}/healthz" >/dev/null; then
    echo "==> OK: gateway is responding on :${VERIFY_PORT}"
else
    echo "==> WARNING: /healthz did not return 200 on :${VERIFY_PORT}; check:" >&2
    echo "    sudo journalctl -u $SERVICE_NAME -n 50" >&2
    exit 1
fi

echo
echo "Done. Useful commands:"
echo "  sudo systemctl status  $SERVICE_NAME"
echo "  sudo journalctl -fu     $SERVICE_NAME"
echo "  sudo systemctl restart  $SERVICE_NAME"
echo
echo "The service is reachable at http://<server-public-ip>:${VERIFY_PORT}/v1"
echo "Health probe: curl http://127.0.0.1:${VERIFY_PORT}/healthz"
echo "Env file (edit then restart): sudo \$EDITOR $ENV_FILE"